var hierarchy =
[
    [ "ADAPT_CLASS_STRUCT", "a02692.html", null ],
    [ "ADAPT_RESULTS", "a02700.html", null ],
    [ "ADAPT_TEMPLATES_STRUCT", "a02696.html", null ],
    [ "ADAPTED_CONFIG", "a02688.html", null ],
    [ "tesseract::AlignedBlobParams", "a03160.html", null ],
    [ "tesseract::AssociateStats", "a03548.html", null ],
    [ "tesseract::AssociateUtils", "a03552.html", null ],
    [ "BAND", "a03208.html", null ],
    [ "tesseract::BaselineBlock", "a03172.html", null ],
    [ "tesseract::BaselineDetect", "a03176.html", null ],
    [ "tesseract::BaselineRow", "a03168.html", null ],
    [ "tesseract::BestChoiceBundle", "a03584.html", null ],
    [ "BITS16", "a02484.html", null ],
    [ "tesseract::BitVector", "a02488.html", null ],
    [ "BlamerBundle", "a02204.html", null ],
    [ "tesseract::BlobData", "a02128.html", null ],
    [ "BLOCK_LINE_IT", "a02396.html", null ],
    [ "BLOCK_RECT_IT", "a02392.html", null ],
    [ "tesseract::BlockGroup", "a03356.html", null ],
    [ "tesseract::BoxChar", "a03364.html", null ],
    [ "tesseract::BoxCharPtrSort", "a03368.html", null ],
    [ "tesseract::BoxWord", "a02240.html", null ],
    [ "BUCKETS", "a02720.html", null ],
    [ "tesseract::CCUtil", "a02492.html", [
      [ "tesseract::CCStruct", "a02244.html", [
        [ "tesseract::Classify", "a02708.html", [
          [ "tesseract::Wordrec", "a03604.html", [
            [ "tesseract::Tesseract", "a02200.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "CHAR_DESC_STRUCT", "a02756.html", null ],
    [ "CHAR_FRAGMENT", "a02656.html", null ],
    [ "CHAR_FRAGMENT_INFO", "a02952.html", null ],
    [ "CHISTRUCT", "a02724.html", null ],
    [ "CLASS_PRUNER_STRUCT", "a02804.html", null ],
    [ "CLASS_STRUCT", "a02876.html", null ],
    [ "tesseract::ClassPruner", "a02776.html", null ],
    [ "tesseract::ClipFFunc", "a02996.html", null ],
    [ "tesseract::ClipFPrime", "a03000.html", null ],
    [ "tesseract::ClipGFunc", "a03020.html", null ],
    [ "tesseract::ClipGPrime", "a03024.html", null ],
    [ "CLIST", "a02500.html", null ],
    [ "CLIST_ITERATOR", "a02504.html", null ],
    [ "CLIST_LINK", "a02496.html", null ],
    [ "tesseract::Cluster", "a02136.html", null ],
    [ "CLUSTERCONFIG", "a02736.html", null ],
    [ "CLUSTERER", "a02748.html", null ],
    [ "ClusteringContext", "a02728.html", null ],
    [ "CP_RESULT_STRUCT", "a02780.html", null ],
    [ "CRACKEDGE", "a02256.html", null ],
    [ "CrackPos", "a03300.html", null ],
    [ "tesseract::CTC", "a03380.html", null ],
    [ "DANGERR_INFO", "a02968.html", null ],
    [ "tesseract::Dawg", "a02928.html", [
      [ "tesseract::SquishedDawg", "a02940.html", null ],
      [ "tesseract::Trie", "a02976.html", null ]
    ] ],
    [ "tesseract::DawgArgs", "a02956.html", null ],
    [ "tesseract::DawgCache", "a02948.html", null ],
    [ "tesseract::DawgLoader", "a02944.html", null ],
    [ "tesseract::DawgPosition", "a02932.html", null ],
    [ "tesseract::DebugPixa", "a02260.html", null ],
    [ "DENORM", "a02340.html", null ],
    [ "tesseract::DetLineFit", "a02264.html", null ],
    [ "tesseract::Dict", "a02960.html", null ],
    [ "DIR128", "a02336.html", null ],
    [ "tesseract::DocumentCache", "a02316.html", null ],
    [ "tesseract::DocumentData", "a02312.html", null ],
    [ "tesseract::DoublePtr", "a02508.html", null ],
    [ "tesseract::DPPoint", "a02272.html", null ],
    [ "EdgeOffset", "a02248.html", null ],
    [ "EDGEPT", "a02224.html", null ],
    [ "MinK< Key, Value >::Element", "a02832.html", null ],
    [ "ELIST", "a02516.html", null ],
    [ "ELIST2", "a02528.html", null ],
    [ "ELIST2_ITERATOR", "a02532.html", null ],
    [ "ELIST2_LINK", "a02524.html", [
      [ "tesseract::ColPartition", "a03248.html", null ],
      [ "tesseract::TabVector", "a03340.html", null ],
      [ "TO_ROW", "a02212.html", null ],
      [ "WERD", "a02468.html", null ]
    ] ],
    [ "ELIST_ITERATOR", "a02520.html", null ],
    [ "ELIST_LINK", "a02512.html", [
      [ "BLOB_CHOICE", "a02432.html", null ],
      [ "BLOBNBOX", "a02208.html", null ],
      [ "BLOCK", "a02344.html", null ],
      [ "BLOCK_RES", "a02364.html", null ],
      [ "C_BLOB", "a02464.html", null ],
      [ "C_OUTLINE", "a02252.html", null ],
      [ "C_OUTLINE_FRAG", "a03276.html", null ],
      [ "FPSEGPT", "a03296.html", null ],
      [ "ICOORDELT", "a02404.html", null ],
      [ "PARA", "a02348.html", null ],
      [ "ParamContent", "a02172.html", null ],
      [ "REGION_OCC", "a03204.html", null ],
      [ "ROW", "a02356.html", null ],
      [ "ROW_RES", "a02368.html", null ],
      [ "SORTED_FLOAT", "a03304.html", null ],
      [ "tesseract::AmbigSpec", "a02476.html", null ],
      [ "tesseract::ColPartitionSet", "a03256.html", null ],
      [ "tesseract::ColSegment", "a03320.html", null ],
      [ "tesseract::FRAGMENT", "a03600.html", null ],
      [ "tesseract::TabConstraint", "a03336.html", null ],
      [ "tesseract::TESS_CHAR", "a02100.html", null ],
      [ "tesseract::TrainingSample", "a02916.html", null ],
      [ "tesseract::ViterbiStateEntry", "a03576.html", null ],
      [ "tesseract::WorkingPartSet", "a03360.html", null ],
      [ "TO_BLOCK", "a02216.html", null ],
      [ "WERD_CHOICE", "a02436.html", null ],
      [ "WERD_RES", "a02372.html", null ]
    ] ],
    [ "tesseract::EquationDetectBase", "a03272.html", [
      [ "tesseract::EquationDetect", "a02120.html", null ]
    ] ],
    [ "ERRCODE", "a02536.html", null ],
    [ "ErrorCode", null, [
      [ "tesseract::IcuErrorCode", "a03408.html", null ]
    ] ],
    [ "tesseract::ErrorCounter", "a03388.html", null ],
    [ "FCOORD", "a02408.html", null ],
    [ "FEATURE_DEFS_STRUCT", "a02760.html", null ],
    [ "FEATURE_DESC_STRUCT", "a02860.html", null ],
    [ "FEATURE_SET_STRUCT", "a02868.html", null ],
    [ "FEATURE_STRUCT", "a02864.html", null ],
    [ "tesseract::FFunc", "a02988.html", null ],
    [ "tesseract::File", "a03396.html", null ],
    [ "FILL_SPEC", "a02800.html", null ],
    [ "FILL_SWITCH", "a02792.html", null ],
    [ "FLOATUNION", "a02740.html", null ],
    [ "tesseract::NetworkScratch::FloatVec", "a03076.html", null ],
    [ "tesseract::FloatWordFeature", "a02304.html", null ],
    [ "tesseract::FontInfo", "a02288.html", null ],
    [ "tesseract::FontSet", "a02292.html", null ],
    [ "tesseract::FontSpacingInfo", "a02284.html", null ],
    [ "tesseract::FontUtils", "a03452.html", null ],
    [ "FPCUTPT", "a03292.html", null ],
    [ "FPOINT", "a02764.html", null ],
    [ "tesseract::FPrime", "a02992.html", null ],
    [ "FRECT", "a03440.html", null ],
    [ "GAPMAP", "a03280.html", null ],
    [ "GENERIC_2D_ARRAY< T >", "a02104.html", [
      [ "BandTriMatrix< T >", "a02324.html", null ]
    ] ],
    [ "GENERIC_2D_ARRAY< BLOB_CHOICE_LIST * >", "a02104.html", [
      [ "BandTriMatrix< BLOB_CHOICE_LIST * >", "a02324.html", [
        [ "MATRIX", "a02328.html", null ]
      ] ]
    ] ],
    [ "GENERIC_2D_ARRAY< double >", "a02104.html", [
      [ "tesseract::TransposedArray", "a03152.html", null ]
    ] ],
    [ "GENERIC_2D_ARRAY< float >", "a02104.html", null ],
    [ "GENERIC_2D_ARRAY< FontClassInfo >", "a02104.html", null ],
    [ "GENERIC_2D_ARRAY< int >", "a02104.html", null ],
    [ "GENERIC_2D_ARRAY< int8_t >", "a02104.html", null ],
    [ "tesseract::GenericHeap< Pair >", "a02540.html", null ],
    [ "tesseract::GenericHeap< MatrixCoordPair >", "a02540.html", null ],
    [ "tesseract::GenericHeap< RecodePair >", "a02540.html", null ],
    [ "tesseract::GenericHeap< tesseract::KDPairInc >", "a02540.html", null ],
    [ "GenericVector< T >", "a02108.html", null ],
    [ "GenericVector< AmbigSpec_LIST * >", "a02108.html", null ],
    [ "GenericVector< BLOBNBOX * >", "a02108.html", null ],
    [ "GenericVector< BLOCK * >", "a02108.html", null ],
    [ "GenericVector< bool >", "a02108.html", null ],
    [ "GenericVector< char >", "a02108.html", null ],
    [ "GenericVector< ColPartitionSet * >", "a02108.html", null ],
    [ "GenericVector< Counts >", "a02108.html", null ],
    [ "GenericVector< CP_RESULT_STRUCT >", "a02108.html", null ],
    [ "GenericVector< DANGERR_INFO >", "a02108.html", null ],
    [ "GenericVector< Dawg * >", "a02108.html", null ],
    [ "GenericVector< DawgPosition >", "a02108.html", [
      [ "tesseract::DawgPositionVector", "a02936.html", null ]
    ] ],
    [ "GenericVector< double >", "a02108.html", null ],
    [ "GenericVector< EDGE_INDEX >", "a02108.html", null ],
    [ "GenericVector< EDGE_RECORD >", "a02108.html", null ],
    [ "GenericVector< float >", "a02108.html", null ],
    [ "GenericVector< FontClassDistance >", "a02108.html", null ],
    [ "GenericVector< FontInfo >", "a02108.html", [
      [ "tesseract::FontInfoTable", "a02296.html", null ]
    ] ],
    [ "GenericVector< GenericVector >", "a02108.html", null ],
    [ "GenericVector< GenericVector< UNICHAR_ID > * >", "a02108.html", null ],
    [ "GenericVector< GenericVectorEqEq< UNICHAR_ID > >", "a02108.html", null ],
    [ "GenericVector< int >", "a02108.html", null ],
    [ "GenericVector< int16_t >", "a02108.html", null ],
    [ "GenericVector< int32_t >", "a02108.html", null ],
    [ "GenericVector< IntKDPair >", "a02108.html", [
      [ "tesseract::KDVector", "a02576.html", null ]
    ] ],
    [ "GenericVector< MatrixCoordPair >", "a02108.html", null ],
    [ "GenericVector< Pair >", "a02108.html", null ],
    [ "GenericVector< ParagraphModel * >", "a02108.html", null ],
    [ "GenericVector< Pix * >", "a02108.html", null ],
    [ "GenericVector< PointWidth >", "a02108.html", null ],
    [ "GenericVector< RecodePair >", "a02108.html", null ],
    [ "GenericVector< ReferenceCount >", "a02108.html", null ],
    [ "GenericVector< SEAM * >", "a02108.html", null ],
    [ "GenericVector< SetOfModels >", "a02108.html", null ],
    [ "GenericVector< SortHelper::SortPair< T > >", "a02108.html", null ],
    [ "GenericVector< STRING >", "a02108.html", null ],
    [ "GenericVector< SuccessorList * >", "a02108.html", null ],
    [ "GenericVector< TBLOB * >", "a02108.html", null ],
    [ "GenericVector< TBOX >", "a02108.html", null ],
    [ "GenericVector< tesseract::BoolParam * >", "a02108.html", null ],
    [ "GenericVector< tesseract::Cluster >", "a02108.html", null ],
    [ "GenericVector< tesseract::ColPartition * >", "a02108.html", null ],
    [ "GenericVector< tesseract::DoubleParam * >", "a02108.html", null ],
    [ "GenericVector< tesseract::FontInfo >", "a02108.html", null ],
    [ "GenericVector< tesseract::FontSet >", "a02108.html", null ],
    [ "GenericVector< tesseract::FontSpacingInfo * >", "a02108.html", null ],
    [ "GenericVector< tesseract::IntParam * >", "a02108.html", null ],
    [ "GenericVector< tesseract::KDPairInc >", "a02108.html", null ],
    [ "GenericVector< tesseract::RecodedCharID >", "a02108.html", null ],
    [ "GenericVector< tesseract::RowScratchRegisters >", "a02108.html", null ],
    [ "GenericVector< tesseract::ScoredFont >", "a02108.html", null ],
    [ "GenericVector< tesseract::StringParam * >", "a02108.html", null ],
    [ "GenericVector< tesseract::Tesseract * >", "a02108.html", null ],
    [ "GenericVector< tesseract::UnicharAndFonts >", "a02108.html", null ],
    [ "GenericVector< TopNState >", "a02108.html", null ],
    [ "GenericVector< TRIE_NODE_RECORD * >", "a02108.html", null ],
    [ "GenericVector< uint16_t >", "a02108.html", null ],
    [ "GenericVector< UNICHAR_ID >", "a02108.html", null ],
    [ "GenericVector< UnicharRating >", "a02108.html", null ],
    [ "tesseract::GeometricClassifierState", "a02144.html", null ],
    [ "tesseract::GFunc", "a03012.html", null ],
    [ "tesseract::GPrime", "a03016.html", null ],
    [ "tesseract::NetworkScratch::GradientStore", "a03080.html", null ],
    [ "tesseract::greater_than", "a03096.html", null ],
    [ "tesseract::GridBase", "a03184.html", [
      [ "tesseract::BBGrid< BLOBNBOX, BLOBNBOX_CLIST, BLOBNBOX_C_IT >", "a03192.html", [
        [ "tesseract::BlobGrid", "a03212.html", [
          [ "tesseract::AlignedBlob", "a03164.html", [
            [ "tesseract::TabFind", "a03316.html", [
              [ "tesseract::ColumnFinder", "a03244.html", null ]
            ] ]
          ] ],
          [ "tesseract::CCNonTextDetect", "a03216.html", null ],
          [ "tesseract::StrokeWidth", "a03312.html", null ]
        ] ]
      ] ],
      [ "tesseract::BBGrid< ColPartition, ColPartition_CLIST, ColPartition_C_IT >", "a03192.html", [
        [ "tesseract::ColPartitionGrid", "a03252.html", null ]
      ] ],
      [ "tesseract::BBGrid< ColSegment, ColSegment_CLIST, ColSegment_C_IT >", "a03192.html", null ],
      [ "tesseract::BBGrid< BBC, BBC_CLIST, BBC_C_IT >", "a03192.html", null ],
      [ "tesseract::IntGrid", "a03188.html", null ]
    ] ],
    [ "tesseract::GridSearch< BBC, BBC_CLIST, BBC_C_IT >", "a03180.html", null ],
    [ "tesseract::HFunc", "a03028.html", null ],
    [ "tesseract::HPrime", "a03032.html", null ],
    [ "ICOORD", "a02400.html", [
      [ "ICOORDELT", "a02404.html", null ]
    ] ],
    [ "tesseract::IdentityFunc", "a03040.html", null ],
    [ "tesseract::ImageData", "a02308.html", null ],
    [ "tesseract::ImageFind", "a03284.html", null ],
    [ "tesseract::StrideMap::Index", "a03132.html", null ],
    [ "tesseract::IndexMap", "a02544.html", [
      [ "tesseract::IndexMapBiDi", "a02548.html", null ]
    ] ],
    [ "tesseract::InputBuffer", "a03400.html", null ],
    [ "INT_CLASS_STRUCT", "a02816.html", null ],
    [ "INT_FEATURE_STRUCT", "a02824.html", null ],
    [ "INT_FX_RESULT_STRUCT", "a02772.html", null ],
    [ "INT_PROTO_STRUCT", "a02808.html", null ],
    [ "INT_TEMPLATES_STRUCT", "a02820.html", null ],
    [ "IntegerMatcher", "a02788.html", null ],
    [ "tesseract::Interval", "a02148.html", null ],
    [ "tesseract::IntFeatureDist", "a03412.html", null ],
    [ "tesseract::IntFeatureMap", "a03416.html", null ],
    [ "tesseract::IntFeatureSpace", "a02768.html", null ],
    [ "tesseract::IntSimdMatrix", "a02112.html", null ],
    [ "tesseract::NetworkScratch::IO", "a03072.html", null ],
    [ "KDNODE", "a02840.html", null ],
    [ "tesseract::KDPair< Key, Data >", "a02552.html", [
      [ "tesseract::KDPairDec< Key, Data >", "a02560.html", null ],
      [ "tesseract::KDPairInc< Key, Data >", "a02556.html", null ]
    ] ],
    [ "tesseract::KDPtrPair< Key, Data >", "a02564.html", [
      [ "tesseract::KDPtrPairDec< Key, Data >", "a02572.html", null ],
      [ "tesseract::KDPtrPairInc< Key, Data >", "a02568.html", null ]
    ] ],
    [ "KDTREE", "a02844.html", null ],
    [ "KDTreeSearch", "a02836.html", null ],
    [ "LABELEDLISTNODE", "a03372.html", null ],
    [ "tesseract::LanguageModel", "a03556.html", null ],
    [ "tesseract::LanguageModelDawgInfo", "a03568.html", null ],
    [ "tesseract::LanguageModelNgramInfo", "a03572.html", null ],
    [ "tesseract::LanguageModelState", "a03580.html", null ],
    [ "tesseract::LigatureTable", "a03420.html", null ],
    [ "tesseract::LineFinder", "a03288.html", null ],
    [ "tesseract::LineHypothesis", "a02156.html", null ],
    [ "list_rec", "a02920.html", null ],
    [ "LLSQ", "a02320.html", null ],
    [ "tesseract::LMConsistencyInfo", "a03560.html", null ],
    [ "tesseract::LMPainPoints", "a03564.html", null ],
    [ "LocalFilePointer", "a02652.html", null ],
    [ "tesseract::LSTMRecognizer", "a03052.html", [
      [ "tesseract::LSTMTrainer", "a03428.html", null ]
    ] ],
    [ "tesseract::LSTMTester", "a03424.html", null ],
    [ "tesseract::MasterTrainer", "a03436.html", null ],
    [ "MATCH_RESULT", "a02964.html", null ],
    [ "MATRIX_COORD", "a02332.html", null ],
    [ "MEASUREMENT", "a03588.html", null ],
    [ "MERGE_CLASS_NODE", "a03376.html", null ],
    [ "Message", null, [
      [ "tesseract::TFNetworkModel", "a03148.html", null ]
    ] ],
    [ "MFEDGEPT", "a02848.html", null ],
    [ "MinK< Key, Value >", "a02828.html", null ],
    [ "MinK< float, void * >", "a02828.html", null ],
    [ "Namespace", null, [
      [ "tesstrain_utils.TrainingArgs", "a03464.html", null ]
    ] ],
    [ "tesseract::Network", "a03060.html", [
      [ "tesseract::Convolve", "a02980.html", null ],
      [ "tesseract::FullyConnected", "a02984.html", null ],
      [ "tesseract::Input", "a03044.html", null ],
      [ "tesseract::LSTM", "a03048.html", null ],
      [ "tesseract::Plumbing", "a03092.html", [
        [ "tesseract::Parallel", "a03088.html", null ],
        [ "tesseract::Reversed", "a03116.html", null ],
        [ "tesseract::Series", "a03120.html", null ]
      ] ],
      [ "tesseract::Reconfig", "a03112.html", [
        [ "tesseract::Maxpool", "a03056.html", null ]
      ] ]
    ] ],
    [ "tesseract::NetworkBuilder", "a03444.html", null ],
    [ "tesseract::NetworkIO", "a03064.html", null ],
    [ "tesseract::NetworkScratch", "a03068.html", null ],
    [ "tesseract::NodeChild", "a02924.html", null ],
    [ "NORM_PROTOS", "a02852.html", null ],
    [ "tesseract::ObjectCache< T >", "a02580.html", null ],
    [ "tesseract::ObjectCache< tesseract::Dawg >", "a02580.html", null ],
    [ "OL_BUCKETS", "a03268.html", null ],
    [ "tesseract::OutputBuffer", "a03404.html", null ],
    [ "PAGE_RES", "a02360.html", null ],
    [ "PAGE_RES_IT", "a02376.html", null ],
    [ "tesseract::PangoFontInfo", "a03448.html", null ],
    [ "ParagraphModel", "a02352.html", null ],
    [ "tesseract::ParagraphModelSmearer", "a02168.html", null ],
    [ "tesseract::ParagraphTheory", "a02164.html", null ],
    [ "tesseract::Param", "a02596.html", [
      [ "tesseract::BoolParam", "a02604.html", null ],
      [ "tesseract::DoubleParam", "a02612.html", null ],
      [ "tesseract::IntParam", "a02600.html", null ],
      [ "tesseract::StringParam", "a02608.html", null ]
    ] ],
    [ "PARAM_DESC", "a02856.html", null ],
    [ "tesseract::ParamsModel", "a03592.html", null ],
    [ "tesseract::ParamsTrainingBundle", "a02384.html", null ],
    [ "tesseract::ParamsTrainingHypothesis", "a02380.html", null ],
    [ "tesseract::ParamsVectors", "a02588.html", null ],
    [ "tesseract::ParamUtils", "a02592.html", null ],
    [ "PB_LINE_IT", "a02416.html", null ],
    [ "PDBLK", "a02388.html", null ],
    [ "PERM_CONFIG_STRUCT", "a02684.html", null ],
    [ "tesseract::PixelHistogram", "a03260.html", null ],
    [ "tesseract::PointerVector< T >", "a02880.html", null ],
    [ "tesseract::PointerVector< GenericVector< double > >", "a02880.html", null ],
    [ "tesseract::PointerVector< RecodeBeam >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::BaselineBlock >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::BaselineRow >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::DocumentData >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::ImageData >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::LanguageModelState >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::Network >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::NetworkIO >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::Shape >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::TrainingSample >", "a02880.html", null ],
    [ "tesseract::PointerVector< tesseract::TransposedArray >", "a02880.html", null ],
    [ "tesseract::PointerVector< WERD_RES >", "a02880.html", null ],
    [ "POLY_BLOCK", "a02412.html", null ],
    [ "PROTO_KEY", "a02704.html", null ],
    [ "PROTO_SET_STRUCT", "a02812.html", null ],
    [ "PROTO_STRUCT", "a02872.html", null ],
    [ "PROTOTYPE", "a02744.html", null ],
    [ "tesseract::PtrHash< T >", "a03196.html", null ],
    [ "QLSQ", "a02420.html", null ],
    [ "QRSequenceGenerator", "a02616.html", null ],
    [ "QSPLINE", "a02428.html", null ],
    [ "QUAD_COEFFS", "a02424.html", null ],
    [ "tesseract::RecodeBeamSearch", "a03104.html", null ],
    [ "tesseract::RecodedCharID", "a02632.html", null ],
    [ "tesseract::RecodedCharID::RecodedCharIDHash", "a02636.html", null ],
    [ "tesseract::RecodeNode", "a03100.html", null ],
    [ "REJ", "a02444.html", null ],
    [ "REJMAP", "a02448.html", null ],
    [ "tesseract::Relu", "a03004.html", null ],
    [ "tesseract::ReluPrime", "a03008.html", null ],
    [ "ResultIterator", null, [
      [ "tesseract::MutableIterator", "a02124.html", null ]
    ] ],
    [ "tesseract::RowInfo", "a02152.html", null ],
    [ "tesseract::RowScratchRegisters", "a02160.html", null ],
    [ "sample", "a02732.html", null ],
    [ "tesseract::SampleIterator", "a03456.html", null ],
    [ "SAMPLELIST", "a02752.html", null ],
    [ "tesseract::ScoredFont", "a02280.html", null ],
    [ "ScratchEvidence", "a02784.html", null ],
    [ "ScrollView", "a03524.html", null ],
    [ "SEAM", "a02452.html", null ],
    [ "tesseract::SegSearchPending", "a03596.html", null ],
    [ "tesseract::Shape", "a02904.html", null ],
    [ "tesseract::ShapeClassifier", "a02884.html", [
      [ "tesseract::TessClassifier", "a02912.html", null ]
    ] ],
    [ "tesseract::ShapeDist", "a03432.html", null ],
    [ "tesseract::ShapeQueueEntry", "a02896.html", null ],
    [ "tesseract::ShapeRating", "a02892.html", null ],
    [ "tesseract::ShapeTable", "a02908.html", null ],
    [ "tesseract::ShiroRekhaSplitter", "a03264.html", null ],
    [ "tesseract::SIMDDetect", "a02116.html", null ],
    [ "tesseract::SimpleClusterer", "a02140.html", null ],
    [ "SORTED_FLOATS", "a03308.html", null ],
    [ "SortHelper< T >", "a02620.html", null ],
    [ "SortHelper< T >::SortPair< PairT >", "a02624.html", null ],
    [ "tesseract::SpacingProperties", "a03468.html", null ],
    [ "SPLIT", "a02456.html", null ],
    [ "tesseract::NetworkScratch::Stack< T >", "a03084.html", null ],
    [ "tesseract::NetworkScratch::Stack< GenericVector< double > >", "a03084.html", null ],
    [ "tesseract::NetworkScratch::Stack< tesseract::NetworkIO >", "a03084.html", null ],
    [ "tesseract::NetworkScratch::Stack< tesseract::TransposedArray >", "a03084.html", null ],
    [ "protobuf_tfnetwork_2eproto::StaticDescriptorInitializer", "a03140.html", null ],
    [ "tesseract::StaticShape", "a03124.html", null ],
    [ "STATISTICS", "a02716.html", null ],
    [ "STATS", "a02460.html", null ],
    [ "tesseract::StrideMap", "a03128.html", null ],
    [ "StringHash", "a03484.html", null ],
    [ "tesseract::StringRenderer", "a03460.html", null ],
    [ "tesseract::StructuredTable", "a03328.html", null ],
    [ "SVEvent", "a03516.html", null ],
    [ "SVEventHandler", "a03520.html", [
      [ "BlnEventHandler", "a02184.html", null ],
      [ "ParamsEditor", "a02180.html", null ],
      [ "PGEventHandler", "a02188.html", null ],
      [ "SVPaint", "a03532.html", null ],
      [ "tesseract::TabEventHandler< G >", "a03200.html", null ]
    ] ],
    [ "SVMenuNode", "a03528.html", null ],
    [ "SVNetwork", "a03544.html", null ],
    [ "SVPolyLineBuffer", "a03512.html", null ],
    [ "SVSemaphore", "a03540.html", null ],
    [ "SVSync", "a03536.html", null ],
    [ "TABLE_FILLER", "a02796.html", null ],
    [ "tesseract::TableFinder", "a03324.html", null ],
    [ "tesseract::TableRecognizer", "a03332.html", null ],
    [ "protobuf_tfnetwork_2eproto::TableStruct", "a03144.html", null ],
    [ "TBLOB", "a02232.html", null ],
    [ "TBOX", "a02440.html", null ],
    [ "TEMP_CONFIG_STRUCT", "a02680.html", null ],
    [ "TEMP_PROTO_STRUCT", "a02676.html", null ],
    [ "TEMPCLUSTER", "a02712.html", null ],
    [ "tesseract::TessdataManager", "a02628.html", null ],
    [ "tesseract::TesseractStats", "a02192.html", null ],
    [ "TESSLINE", "a02228.html", null ],
    [ "tesseract::TextlineProjection", "a03344.html", null ],
    [ "tesseract::Textord", "a03352.html", null ],
    [ "tesseract::TFNetworkModelDefaultTypeInternal", "a03136.html", null ],
    [ "TPOINT", "a02220.html", null ],
    [ "tesseract::TrainingSampleSet", "a03472.html", null ],
    [ "TRIE_NODE_RECORD", "a02972.html", null ],
    [ "TWERD", "a02236.html", null ],
    [ "tesseract::UnicharAmbigs", "a02480.html", null ],
    [ "tesseract::UnicharAndFonts", "a02900.html", null ],
    [ "tesseract::UnicharCompress", "a02640.html", null ],
    [ "tesseract::UnicharIdArrayUtils", "a02472.html", null ],
    [ "UNICHARMAP", "a02644.html", null ],
    [ "tesseract::UnicharRating", "a02888.html", null ],
    [ "UNICHARSET", "a02660.html", null ],
    [ "UnicityTable< T >", "a02276.html", [
      [ "UnicityTableEqEq< T >", "a02672.html", null ]
    ] ],
    [ "UnicityTable< int >", "a02276.html", [
      [ "UnicityTableEqEq< int >", "a02672.html", null ]
    ] ],
    [ "UnicityTable< tesseract::FontInfo >", "a02276.html", null ],
    [ "UnicityTable< tesseract::FontSet >", "a02276.html", null ],
    [ "tesseract::UnicodeSpanSkipper", "a02132.html", null ],
    [ "tesseract::UnityFunc", "a03036.html", null ],
    [ "tesseract::Validator", "a03508.html", [
      [ "tesseract::ValidateGrapheme", "a03488.html", null ],
      [ "tesseract::ValidateIndic", "a03492.html", null ],
      [ "tesseract::ValidateJavanese", "a03496.html", null ],
      [ "tesseract::ValidateKhmer", "a03500.html", null ],
      [ "tesseract::ValidateMyanmar", "a03504.html", null ]
    ] ],
    [ "tesseract::WeightMatrix", "a03156.html", null ],
    [ "tesseract::WordData", "a02196.html", null ],
    [ "tesseract::WordFeature", "a02300.html", null ],
    [ "WordOutputter", "a03384.html", null ],
    [ "tesseract::WordWithBox", "a03348.html", null ]
];