var hierarchy =
[
    [ "ADAPT_CLASS_STRUCT", "a03150.html", null ],
    [ "ADAPT_RESULTS", "a03158.html", null ],
    [ "ADAPT_TEMPLATES_STRUCT", "a03154.html", null ],
    [ "ADAPTED_CONFIG", "a03146.html", null ],
    [ "tesseract::AlignedBlobParams", "a03614.html", null ],
    [ "tesseract::AssociateStats", "a04002.html", null ],
    [ "tesseract::AssociateUtils", "a04006.html", null ],
    [ "BAND", "a03662.html", null ],
    [ "tesseract::BaselineBlock", "a03626.html", null ],
    [ "tesseract::BaselineDetect", "a03630.html", null ],
    [ "tesseract::BaselineRow", "a03622.html", null ],
    [ "tesseract::BestChoiceBundle", "a04038.html", null ],
    [ "BitReader", "a04126.html", null ],
    [ "BITS16", "a02942.html", null ],
    [ "tesseract::BitVector", "a02946.html", null ],
    [ "BlamerBundle", "a02662.html", null ],
    [ "tesseract::BlobData", "a02586.html", null ],
    [ "BLOCK_LINE_IT", "a02854.html", null ],
    [ "BLOCK_RECT_IT", "a02850.html", null ],
    [ "tesseract::BlockGroup", "a03810.html", null ],
    [ "tesseract::BoxChar", "a03818.html", null ],
    [ "tesseract::BoxCharPtrSort", "a03822.html", null ],
    [ "tesseract::BoxWord", "a02698.html", null ],
    [ "BUCKETS", "a03178.html", null ],
    [ "tesseract::CCUtil", "a02950.html", [
      [ "tesseract::CCStruct", "a02702.html", [
        [ "tesseract::Classify", "a03166.html", [
          [ "tesseract::Wordrec", "a04058.html", [
            [ "tesseract::Tesseract", "a02658.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "CHAR_DESC_STRUCT", "a03214.html", null ],
    [ "CHAR_FRAGMENT", "a03114.html", null ],
    [ "CHAR_FRAGMENT_INFO", "a03406.html", null ],
    [ "CHISTRUCT", "a03182.html", null ],
    [ "tesseract::ChoiceIterator", "a02458.html", null ],
    [ "CLASS_PRUNER_STRUCT", "a03262.html", null ],
    [ "CLASS_STRUCT", "a03334.html", null ],
    [ "tesseract::ClassPruner", "a03234.html", null ],
    [ "tesseract::ClipFFunc", "a03450.html", null ],
    [ "tesseract::ClipFPrime", "a03454.html", null ],
    [ "tesseract::ClipGFunc", "a03474.html", null ],
    [ "tesseract::ClipGPrime", "a03478.html", null ],
    [ "CLIST", "a02958.html", null ],
    [ "CLIST_ITERATOR", "a02962.html", null ],
    [ "CLIST_LINK", "a02954.html", null ],
    [ "tesseract::Cluster", "a02594.html", null ],
    [ "CLUSTERCONFIG", "a03194.html", null ],
    [ "CLUSTERER", "a03206.html", null ],
    [ "ClusteringContext", "a03186.html", null ],
    [ "UnicodeText::const_iterator", "a04350.html", null ],
    [ "tesseract::UNICHAR::const_iterator", "a02558.html", null ],
    [ "CP_RESULT_STRUCT", "a03238.html", null ],
    [ "CRACKEDGE", "a02714.html", null ],
    [ "CrackPos", "a03754.html", null ],
    [ "tesseract::CTC", "a03834.html", null ],
    [ "CycleTimer", "a04106.html", null ],
    [ "DANGERR_INFO", "a03422.html", null ],
    [ "tesseract::Dawg", "a03382.html", [
      [ "tesseract::SquishedDawg", "a03394.html", null ],
      [ "tesseract::Trie", "a03430.html", null ]
    ] ],
    [ "tesseract::DawgArgs", "a03410.html", null ],
    [ "tesseract::DawgCache", "a03402.html", null ],
    [ "tesseract::DawgLoader", "a03398.html", null ],
    [ "tesseract::DawgPosition", "a03386.html", null ],
    [ "tesseract::DebugPixa", "a02718.html", null ],
    [ "DENORM", "a02798.html", null ],
    [ "tesseract::DetLineFit", "a02722.html", null ],
    [ "tesseract::Dict", "a03414.html", null ],
    [ "DIR128", "a02794.html", null ],
    [ "tesseract::DocumentCache", "a02774.html", null ],
    [ "tesseract::DocumentData", "a02770.html", null ],
    [ "tesseract::DoublePtr", "a02966.html", null ],
    [ "tesseract::DPPoint", "a02730.html", null ],
    [ "EANYCODE_CHAR", "a02462.html", null ],
    [ "EdgeOffset", "a02706.html", null ],
    [ "EDGEPT", "a02682.html", null ],
    [ "MinK< Key, Value >::Element", "a03290.html", null ],
    [ "ELIST", "a02974.html", null ],
    [ "ELIST2", "a02986.html", null ],
    [ "ELIST2_ITERATOR", "a02990.html", null ],
    [ "ELIST2_LINK", "a02982.html", [
      [ "tesseract::ColPartition", "a03702.html", null ],
      [ "tesseract::TabVector", "a03794.html", null ],
      [ "TO_ROW", "a02670.html", null ],
      [ "WERD", "a02926.html", null ]
    ] ],
    [ "ELIST_ITERATOR", "a02978.html", null ],
    [ "ELIST_LINK", "a02970.html", [
      [ "BLOB_CHOICE", "a02890.html", null ],
      [ "BLOBNBOX", "a02666.html", null ],
      [ "BLOCK", "a02802.html", null ],
      [ "BLOCK_RES", "a02822.html", null ],
      [ "C_BLOB", "a02922.html", null ],
      [ "C_OUTLINE", "a02710.html", null ],
      [ "C_OUTLINE_FRAG", "a03730.html", null ],
      [ "FPSEGPT", "a03750.html", null ],
      [ "ICOORDELT", "a02862.html", null ],
      [ "PARA", "a02806.html", null ],
      [ "ParamContent", "a02630.html", null ],
      [ "REGION_OCC", "a03658.html", null ],
      [ "ROW", "a02814.html", null ],
      [ "ROW_RES", "a02826.html", null ],
      [ "SORTED_FLOAT", "a03758.html", null ],
      [ "tesseract::AmbigSpec", "a02934.html", null ],
      [ "tesseract::ColPartitionSet", "a03710.html", null ],
      [ "tesseract::ColSegment", "a03774.html", null ],
      [ "tesseract::FRAGMENT", "a04054.html", null ],
      [ "tesseract::TabConstraint", "a03790.html", null ],
      [ "tesseract::TESS_CHAR", "a02562.html", null ],
      [ "tesseract::TrainingSample", "a03370.html", null ],
      [ "tesseract::ViterbiStateEntry", "a04030.html", null ],
      [ "tesseract::WorkingPartSet", "a03814.html", null ],
      [ "TO_BLOCK", "a02674.html", null ],
      [ "WERD_CHOICE", "a02894.html", null ],
      [ "WERD_RES", "a02830.html", null ]
    ] ],
    [ "tesseract::EquationDetectBase", "a03726.html", [
      [ "tesseract::EquationDetect", "a02578.html", [
        [ "tesseract::TestableEquationDetect", "a04118.html", null ]
      ] ]
    ] ],
    [ "ERRCODE", "a02994.html", null ],
    [ "ErrorCode", null, [
      [ "tesseract::IcuErrorCode", "a03862.html", null ]
    ] ],
    [ "tesseract::ErrorCounter", "a03842.html", null ],
    [ "ETEXT_DESC", "a02466.html", null ],
    [ "FCOORD", "a02866.html", null ],
    [ "FEATURE_DEFS_STRUCT", "a03218.html", null ],
    [ "FEATURE_DESC_STRUCT", "a03318.html", null ],
    [ "FEATURE_SET_STRUCT", "a03326.html", null ],
    [ "FEATURE_STRUCT", "a03322.html", null ],
    [ "tesseract::FFunc", "a03442.html", null ],
    [ "tesseract::File", "a03850.html", [
      [ "file", "a04138.html", null ]
    ] ],
    [ "FILL_SPEC", "a03258.html", null ],
    [ "FILL_SWITCH", "a03250.html", null ],
    [ "FLOATUNION", "a03198.html", null ],
    [ "tesseract::NetworkScratch::FloatVec", "a03530.html", null ],
    [ "tesseract::FloatWordFeature", "a02762.html", null ],
    [ "tesseract::FontInfo", "a02746.html", null ],
    [ "tesseract::FontSet", "a02750.html", null ],
    [ "tesseract::FontSpacingInfo", "a02742.html", null ],
    [ "tesseract::FontUtils", "a03906.html", null ],
    [ "FPCUTPT", "a03746.html", null ],
    [ "FPOINT", "a03222.html", null ],
    [ "tesseract::FPrime", "a03446.html", null ],
    [ "FRECT", "a03894.html", null ],
    [ "GAPMAP", "a03734.html", null ],
    [ "GENERIC_2D_ARRAY< T >", "a02566.html", [
      [ "BandTriMatrix< T >", "a02782.html", null ]
    ] ],
    [ "GENERIC_2D_ARRAY< BLOB_CHOICE_LIST * >", "a02566.html", [
      [ "BandTriMatrix< BLOB_CHOICE_LIST * >", "a02782.html", [
        [ "MATRIX", "a02786.html", null ]
      ] ]
    ] ],
    [ "GENERIC_2D_ARRAY< double >", "a02566.html", [
      [ "tesseract::TransposedArray", "a03606.html", null ]
    ] ],
    [ "GENERIC_2D_ARRAY< float >", "a02566.html", null ],
    [ "GENERIC_2D_ARRAY< FontClassInfo >", "a02566.html", null ],
    [ "GENERIC_2D_ARRAY< int >", "a02566.html", null ],
    [ "GENERIC_2D_ARRAY< int8_t >", "a02566.html", null ],
    [ "tesseract::GenericHeap< Pair >", "a02998.html", null ],
    [ "tesseract::GenericHeap< MatrixCoordPair >", "a02998.html", null ],
    [ "tesseract::GenericHeap< RecodePair >", "a02998.html", null ],
    [ "tesseract::GenericHeap< tesseract::KDPairInc >", "a02998.html", null ],
    [ "GenericVector< T >", "a02434.html", [
      [ "GenericVectorEqEq< T >", "a02446.html", null ],
      [ "GenericVectorEqEq< tesseract::LineHypothesis >", "a02446.html", null ],
      [ "tesseract::PointerVector< GenericVector< double > >", "a02442.html", null ],
      [ "tesseract::PointerVector< RecodeBeam >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::BaselineBlock >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::BaselineRow >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::DocumentData >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::ImageData >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::LanguageModelState >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::Network >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::NetworkIO >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::Shape >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::TrainingSample >", "a02442.html", null ],
      [ "tesseract::PointerVector< tesseract::TransposedArray >", "a02442.html", null ],
      [ "tesseract::PointerVector< WERD_RES >", "a02442.html", null ]
    ] ],
    [ "GenericVector< AmbigSpec_LIST * >", "a02434.html", null ],
    [ "GenericVector< BLOBNBOX * >", "a02434.html", null ],
    [ "GenericVector< BLOCK * >", "a02434.html", null ],
    [ "GenericVector< bool >", "a02434.html", null ],
    [ "GenericVector< char >", "a02434.html", null ],
    [ "GenericVector< ColPartitionSet * >", "a02434.html", null ],
    [ "GenericVector< Counts >", "a02434.html", null ],
    [ "GenericVector< CP_RESULT_STRUCT >", "a02434.html", null ],
    [ "GenericVector< DANGERR_INFO >", "a02434.html", null ],
    [ "GenericVector< Dawg * >", "a02434.html", null ],
    [ "GenericVector< DawgPosition >", "a02434.html", [
      [ "tesseract::DawgPositionVector", "a03390.html", null ]
    ] ],
    [ "GenericVector< double >", "a02434.html", null ],
    [ "GenericVector< EDGE_INDEX >", "a02434.html", null ],
    [ "GenericVector< EDGE_RECORD >", "a02434.html", null ],
    [ "GenericVector< float >", "a02434.html", null ],
    [ "GenericVector< FontClassDistance >", "a02434.html", null ],
    [ "GenericVector< FontInfo >", "a02434.html", [
      [ "tesseract::FontInfoTable", "a02754.html", null ]
    ] ],
    [ "GenericVector< GenericVector >", "a02434.html", null ],
    [ "GenericVector< GenericVector< UNICHAR_ID > * >", "a02434.html", null ],
    [ "GenericVector< GenericVectorEqEq >", "a02434.html", null ],
    [ "GenericVector< GenericVectorEqEq< UNICHAR_ID > >", "a02434.html", null ],
    [ "GenericVector< int >", "a02434.html", [
      [ "GenericVectorEqEq< int >", "a02446.html", null ]
    ] ],
    [ "GenericVector< int16_t >", "a02434.html", null ],
    [ "GenericVector< int32_t >", "a02434.html", null ],
    [ "GenericVector< IntKDPair >", "a02434.html", [
      [ "tesseract::KDVector", "a03034.html", null ]
    ] ],
    [ "GenericVector< long int >", "a02434.html", null ],
    [ "GenericVector< MatrixCoordPair >", "a02434.html", null ],
    [ "GenericVector< Pair >", "a02434.html", null ],
    [ "GenericVector< ParagraphModel * >", "a02434.html", [
      [ "GenericVectorEqEq< ParagraphModel * >", "a02446.html", null ]
    ] ],
    [ "GenericVector< Pix * >", "a02434.html", null ],
    [ "GenericVector< PointWidth >", "a02434.html", null ],
    [ "GenericVector< RecodePair >", "a02434.html", null ],
    [ "GenericVector< ReferenceCount >", "a02434.html", null ],
    [ "GenericVector< SEAM * >", "a02434.html", null ],
    [ "GenericVector< SortHelper::SortPair< T > >", "a02434.html", null ],
    [ "GenericVector< STRING >", "a02434.html", null ],
    [ "GenericVector< SuccessorList * >", "a02434.html", null ],
    [ "GenericVector< T * >", "a02434.html", [
      [ "tesseract::PointerVector< T >", "a02442.html", null ]
    ] ],
    [ "GenericVector< TBLOB * >", "a02434.html", null ],
    [ "GenericVector< TBOX >", "a02434.html", null ],
    [ "GenericVector< tesseract::BoolParam * >", "a02434.html", null ],
    [ "GenericVector< tesseract::Cluster >", "a02434.html", null ],
    [ "GenericVector< tesseract::ColPartition * >", "a02434.html", null ],
    [ "GenericVector< tesseract::DoubleParam * >", "a02434.html", null ],
    [ "GenericVector< tesseract::FontInfo >", "a02434.html", null ],
    [ "GenericVector< tesseract::FontSet >", "a02434.html", null ],
    [ "GenericVector< tesseract::FontSpacingInfo * >", "a02434.html", null ],
    [ "GenericVector< tesseract::IntParam * >", "a02434.html", null ],
    [ "GenericVector< tesseract::KDPairInc >", "a02434.html", null ],
    [ "GenericVector< tesseract::RecodedCharID >", "a02434.html", null ],
    [ "GenericVector< tesseract::RowScratchRegisters >", "a02434.html", null ],
    [ "GenericVector< tesseract::ScoredFont >", "a02434.html", null ],
    [ "GenericVector< tesseract::StringParam * >", "a02434.html", null ],
    [ "GenericVector< tesseract::Tesseract * >", "a02434.html", null ],
    [ "GenericVector< tesseract::UnicharAndFonts >", "a02434.html", null ],
    [ "GenericVector< TopNState >", "a02434.html", null ],
    [ "GenericVector< TRIE_NODE_RECORD * >", "a02434.html", null ],
    [ "GenericVector< uint16_t >", "a02434.html", null ],
    [ "GenericVector< UNICHAR_ID >", "a02434.html", [
      [ "GenericVectorEqEq< UNICHAR_ID >", "a02446.html", null ]
    ] ],
    [ "GenericVector< UnicharRating >", "a02434.html", null ],
    [ "tesseract::GeometricClassifierState", "a02602.html", null ],
    [ "tesseract::GFunc", "a03466.html", null ],
    [ "tesseract::GPrime", "a03470.html", null ],
    [ "tesseract::NetworkScratch::GradientStore", "a03534.html", null ],
    [ "tesseract::greater_than", "a03550.html", null ],
    [ "tesseract::GridBase", "a03638.html", [
      [ "tesseract::BBGrid< BLOBNBOX, BLOBNBOX_CLIST, BLOBNBOX_C_IT >", "a03646.html", [
        [ "tesseract::BlobGrid", "a03666.html", [
          [ "tesseract::AlignedBlob", "a03618.html", [
            [ "tesseract::TabFind", "a03770.html", [
              [ "tesseract::ColumnFinder", "a03698.html", null ]
            ] ]
          ] ],
          [ "tesseract::CCNonTextDetect", "a03670.html", null ],
          [ "tesseract::StrokeWidth", "a03766.html", null ]
        ] ]
      ] ],
      [ "tesseract::BBGrid< ColPartition, ColPartition_CLIST, ColPartition_C_IT >", "a03646.html", [
        [ "tesseract::ColPartitionGrid", "a03706.html", null ]
      ] ],
      [ "tesseract::BBGrid< ColSegment, ColSegment_CLIST, ColSegment_C_IT >", "a03646.html", null ],
      [ "tesseract::BBGrid< BBC, BBC_CLIST, BBC_C_IT >", "a03646.html", null ],
      [ "tesseract::IntGrid", "a03642.html", null ]
    ] ],
    [ "tesseract::GridSearch< BBC, BBC_CLIST, BBC_C_IT >", "a03634.html", null ],
    [ "tesseract::HFunc", "a03482.html", null ],
    [ "tesseract::HPrime", "a03486.html", null ],
    [ "ICOORD", "a02858.html", [
      [ "ICOORDELT", "a02862.html", null ]
    ] ],
    [ "tesseract::IdentityFunc", "a03494.html", null ],
    [ "tesseract::ImageData", "a02766.html", null ],
    [ "tesseract::ImageFind", "a03738.html", null ],
    [ "tesseract::ImageThresholder", "a02550.html", null ],
    [ "tesseract::StrideMap::Index", "a03586.html", null ],
    [ "tesseract::IndexMap", "a03002.html", [
      [ "tesseract::IndexMapBiDi", "a03006.html", null ]
    ] ],
    [ "tesseract::InputBuffer", "a03854.html", null ],
    [ "INT_CLASS_STRUCT", "a03274.html", null ],
    [ "INT_FEATURE_STRUCT", "a03282.html", null ],
    [ "INT_FX_RESULT_STRUCT", "a03230.html", null ],
    [ "INT_PROTO_STRUCT", "a03266.html", null ],
    [ "INT_TEMPLATES_STRUCT", "a03278.html", null ],
    [ "IntegerMatcher", "a03246.html", null ],
    [ "tesseract::Interval", "a02606.html", null ],
    [ "tesseract::IntFeatureDist", "a03866.html", null ],
    [ "tesseract::IntFeatureMap", "a03870.html", null ],
    [ "tesseract::IntFeatureSpace", "a03226.html", null ],
    [ "tesseract::IntSimdMatrix", "a02570.html", null ],
    [ "tesseract::NetworkScratch::IO", "a03526.html", null ],
    [ "KDNODE", "a03298.html", null ],
    [ "tesseract::KDPair< Key, Data >", "a03010.html", [
      [ "tesseract::KDPairDec< Key, Data >", "a03018.html", null ],
      [ "tesseract::KDPairInc< Key, Data >", "a03014.html", null ]
    ] ],
    [ "tesseract::KDPtrPair< Key, Data >", "a03022.html", [
      [ "tesseract::KDPtrPairDec< Key, Data >", "a03030.html", null ],
      [ "tesseract::KDPtrPairInc< Key, Data >", "a03026.html", null ]
    ] ],
    [ "KDTREE", "a03302.html", null ],
    [ "KDTreeSearch", "a03294.html", null ],
    [ "LABELEDLISTNODE", "a03826.html", null ],
    [ "tesseract::LanguageModel", "a04010.html", null ],
    [ "tesseract::LanguageModelDawgInfo", "a04022.html", null ],
    [ "tesseract::LanguageModelNgramInfo", "a04026.html", null ],
    [ "tesseract::LanguageModelState", "a04034.html", null ],
    [ "tesseract::LigatureTable", "a03874.html", null ],
    [ "tesseract::LineFinder", "a03742.html", null ],
    [ "tesseract::LineHypothesis", "a02614.html", null ],
    [ "list_rec", "a03374.html", null ],
    [ "LLSQ", "a02778.html", null ],
    [ "tesseract::LMConsistencyInfo", "a04014.html", null ],
    [ "tesseract::LMPainPoints", "a04018.html", null ],
    [ "LocalFilePointer", "a03110.html", null ],
    [ "tesseract::LSTMRecognizer", "a03506.html", [
      [ "tesseract::LSTMTrainer", "a03882.html", null ]
    ] ],
    [ "tesseract::LSTMTester", "a03878.html", null ],
    [ "tesseract::MasterTrainer", "a03890.html", null ],
    [ "MATCH_RESULT", "a03418.html", null ],
    [ "MATRIX_COORD", "a02790.html", null ],
    [ "MEASUREMENT", "a04042.html", null ],
    [ "MERGE_CLASS_NODE", "a03830.html", null ],
    [ "Message", null, [
      [ "tesseract::TFNetworkModel", "a03602.html", null ]
    ] ],
    [ "MFEDGEPT", "a03306.html", null ],
    [ "MinK< Key, Value >", "a03286.html", null ],
    [ "MinK< float, void * >", "a03286.html", null ],
    [ "Namespace", null, [
      [ "tesstrain_utils.TrainingArgs", "a03918.html", null ]
    ] ],
    [ "tesseract::Network", "a03514.html", [
      [ "tesseract::Convolve", "a03434.html", null ],
      [ "tesseract::FullyConnected", "a03438.html", null ],
      [ "tesseract::Input", "a03498.html", null ],
      [ "tesseract::LSTM", "a03502.html", null ],
      [ "tesseract::Plumbing", "a03546.html", [
        [ "tesseract::Parallel", "a03542.html", null ],
        [ "tesseract::Reversed", "a03570.html", null ],
        [ "tesseract::Series", "a03574.html", null ]
      ] ],
      [ "tesseract::Reconfig", "a03566.html", [
        [ "tesseract::Maxpool", "a03510.html", null ]
      ] ]
    ] ],
    [ "tesseract::NetworkBuilder", "a03898.html", null ],
    [ "tesseract::NetworkIO", "a03518.html", null ],
    [ "tesseract::NetworkScratch", "a03522.html", null ],
    [ "tesseract::NodeChild", "a03378.html", null ],
    [ "NORM_PROTOS", "a03310.html", null ],
    [ "tesseract::ObjectCache< T >", "a03038.html", null ],
    [ "tesseract::ObjectCache< tesseract::Dawg >", "a03038.html", null ],
    [ "OL_BUCKETS", "a03722.html", null ],
    [ "OrientationDetector", "a02478.html", null ],
    [ "OSBestResult", "a02470.html", null ],
    [ "OSResults", "a02474.html", null ],
    [ "tesseract::OutputBuffer", "a03858.html", null ],
    [ "PAGE_RES", "a02818.html", null ],
    [ "PAGE_RES_IT", "a02834.html", null ],
    [ "tesseract::PageIterator", "a02486.html", [
      [ "tesseract::LTRResultIterator", "a02454.html", [
        [ "tesseract::ResultIterator", "a02534.html", [
          [ "tesseract::MutableIterator", "a02582.html", null ]
        ] ]
      ] ]
    ] ],
    [ "tesseract::PangoFontInfo", "a03902.html", null ],
    [ "ParagraphModel", "a02810.html", null ],
    [ "tesseract::ParagraphModelSmearer", "a02626.html", null ],
    [ "tesseract::ParagraphTheory", "a02622.html", null ],
    [ "tesseract::Param", "a03054.html", [
      [ "tesseract::BoolParam", "a03062.html", null ],
      [ "tesseract::DoubleParam", "a03070.html", null ],
      [ "tesseract::IntParam", "a03058.html", null ],
      [ "tesseract::StringParam", "a03066.html", null ]
    ] ],
    [ "PARAM_DESC", "a03314.html", null ],
    [ "tesseract::ParamsModel", "a04046.html", null ],
    [ "tesseract::ParamsTrainingBundle", "a02842.html", null ],
    [ "tesseract::ParamsTrainingHypothesis", "a02838.html", null ],
    [ "tesseract::ParamsVectors", "a03046.html", null ],
    [ "tesseract::ParamUtils", "a03050.html", null ],
    [ "PB_LINE_IT", "a02874.html", null ],
    [ "PDBLK", "a02846.html", null ],
    [ "PERM_CONFIG_STRUCT", "a03142.html", null ],
    [ "tesseract::PixelHistogram", "a03714.html", null ],
    [ "POLY_BLOCK", "a02870.html", null ],
    [ "PROTO_KEY", "a03162.html", null ],
    [ "PROTO_SET_STRUCT", "a03270.html", null ],
    [ "PROTO_STRUCT", "a03330.html", null ],
    [ "PROTOTYPE", "a03202.html", null ],
    [ "tesseract::PtrHash< T >", "a03650.html", null ],
    [ "QLSQ", "a02878.html", null ],
    [ "QRSequenceGenerator", "a03074.html", null ],
    [ "QSPLINE", "a02886.html", null ],
    [ "QUAD_COEFFS", "a02882.html", null ],
    [ "tesseract::RecodeBeamSearch", "a03558.html", null ],
    [ "tesseract::RecodedCharID", "a03090.html", null ],
    [ "tesseract::RecodedCharID::RecodedCharIDHash", "a03094.html", null ],
    [ "tesseract::RecodeNode", "a03554.html", null ],
    [ "REJ", "a02902.html", null ],
    [ "REJMAP", "a02906.html", null ],
    [ "tesseract::Relu", "a03458.html", null ],
    [ "tesseract::ReluPrime", "a03462.html", null ],
    [ "reverse_iterator", null, [
      [ "UnicodeText::const_reverse_iterator", "a04354.html", null ]
    ] ],
    [ "tesseract::RowInfo", "a02610.html", null ],
    [ "tesseract::RowScratchRegisters", "a02618.html", null ],
    [ "sample", "a03190.html", null ],
    [ "tesseract::SampleIterator", "a03910.html", null ],
    [ "SAMPLELIST", "a03210.html", null ],
    [ "tesseract::ScoredFont", "a02738.html", null ],
    [ "ScratchEvidence", "a03242.html", null ],
    [ "ScriptDetector", "a02482.html", null ],
    [ "ScrollView", "a03978.html", null ],
    [ "SEAM", "a02910.html", null ],
    [ "tesseract::SegSearchPending", "a04050.html", null ],
    [ "tesseract::Shape", "a03358.html", null ],
    [ "tesseract::ShapeClassifier", "a03338.html", [
      [ "tesseract::MockClassifier", "a04186.html", null ],
      [ "tesseract::TessClassifier", "a03366.html", null ]
    ] ],
    [ "tesseract::ShapeDist", "a03886.html", null ],
    [ "tesseract::ShapeQueueEntry", "a03350.html", null ],
    [ "tesseract::ShapeRating", "a03346.html", null ],
    [ "tesseract::ShapeTable", "a03362.html", null ],
    [ "tesseract::ShiroRekhaSplitter", "a03718.html", null ],
    [ "tesseract::SIMDDetect", "a02574.html", null ],
    [ "tesseract::SimpleClusterer", "a02598.html", null ],
    [ "SORTED_FLOATS", "a03762.html", null ],
    [ "SortHelper< T >", "a03078.html", null ],
    [ "SortHelper< T >::SortPair< PairT >", "a03082.html", null ],
    [ "SortHelper< T >::SortPair< T >", "a03082.html", null ],
    [ "tesseract::SpacingProperties", "a03922.html", null ],
    [ "SPLIT", "a02914.html", null ],
    [ "tesseract::NetworkScratch::Stack< T >", "a03538.html", null ],
    [ "tesseract::NetworkScratch::Stack< GenericVector< double > >", "a03538.html", null ],
    [ "tesseract::NetworkScratch::Stack< tesseract::NetworkIO >", "a03538.html", null ],
    [ "tesseract::NetworkScratch::Stack< tesseract::TransposedArray >", "a03538.html", null ],
    [ "protobuf_tfnetwork_2eproto::StaticDescriptorInitializer", "a03594.html", null ],
    [ "tesseract::StaticShape", "a03578.html", null ],
    [ "STATISTICS", "a03174.html", null ],
    [ "STATS", "a02918.html", null ],
    [ "tesseract::StrideMap", "a03582.html", null ],
    [ "STRING", "a02542.html", null ],
    [ "StringHash", "a03938.html", null ],
    [ "tesseract::StringRenderer", "a03914.html", null ],
    [ "tesseract::StructuredTable", "a03782.html", null ],
    [ "SVEvent", "a03970.html", null ],
    [ "SVEventHandler", "a03974.html", [
      [ "BlnEventHandler", "a02642.html", null ],
      [ "ParamsEditor", "a02638.html", null ],
      [ "PGEventHandler", "a02646.html", null ],
      [ "SVPaint", "a03986.html", null ],
      [ "tesseract::TabEventHandler< G >", "a03654.html", null ]
    ] ],
    [ "SVMenuNode", "a03982.html", null ],
    [ "SVNetwork", "a03998.html", null ],
    [ "SVPolyLineBuffer", "a03966.html", null ],
    [ "SVSemaphore", "a03994.html", null ],
    [ "SVSync", "a03990.html", null ],
    [ "TABLE_FILLER", "a03254.html", null ],
    [ "tesseract::TableFinder", "a03778.html", null ],
    [ "tesseract::TableRecognizer", "a03786.html", null ],
    [ "protobuf_tfnetwork_2eproto::TableStruct", "a03598.html", null ],
    [ "TBLOB", "a02690.html", null ],
    [ "TBOX", "a02898.html", null ],
    [ "TEMP_CONFIG_STRUCT", "a03138.html", null ],
    [ "TEMP_PROTO_STRUCT", "a03134.html", null ],
    [ "TEMPCLUSTER", "a03170.html", null ],
    [ "tesseract::TessBaseAPI", "a02438.html", null ],
    [ "tesseract::TessdataManager", "a03086.html", null ],
    [ "tesseract::TesseractStats", "a02650.html", null ],
    [ "TESSLINE", "a02686.html", null ],
    [ "tesseract::TessResultRenderer", "a02490.html", [
      [ "tesseract::TessAltoRenderer", "a02502.html", null ],
      [ "tesseract::TessBoxTextRenderer", "a02522.html", null ],
      [ "tesseract::TessHOcrRenderer", "a02498.html", null ],
      [ "tesseract::TessLSTMBoxRenderer", "a02518.html", null ],
      [ "tesseract::TessOsdRenderer", "a02530.html", null ],
      [ "tesseract::TessPDFRenderer", "a02510.html", null ],
      [ "tesseract::TessTextRenderer", "a02494.html", null ],
      [ "tesseract::TessTsvRenderer", "a02506.html", null ],
      [ "tesseract::TessUnlvRenderer", "a02514.html", null ],
      [ "tesseract::TessWordStrBoxRenderer", "a02526.html", null ]
    ] ],
    [ "Test", null, [
      [ "tesseract::EquationFinderTest", "a04122.html", null ],
      [ "tesseract::HeapTest", "a04130.html", null ],
      [ "tesseract::LSTMTrainerTest", "a04182.html", null ],
      [ "tesseract::NthItemTest", "a04202.html", null ]
    ] ],
    [ "tesseract::TextlineProjection", "a03798.html", null ],
    [ "tesseract::Textord", "a03806.html", null ],
    [ "tesseract::TFile", "a02538.html", null ],
    [ "tesseract::TFNetworkModelDefaultTypeInternal", "a03590.html", null ],
    [ "TPOINT", "a02678.html", null ],
    [ "tesseract::TrainingSampleSet", "a03926.html", null ],
    [ "tesseract::TRand", "a02450.html", null ],
    [ "TRIE_NODE_RECORD", "a03426.html", null ],
    [ "TWERD", "a02694.html", null ],
    [ "tesseract::UNICHAR", "a02554.html", null ],
    [ "tesseract::UnicharAmbigs", "a02938.html", null ],
    [ "tesseract::UnicharAndFonts", "a03354.html", null ],
    [ "tesseract::UnicharCompress", "a03098.html", null ],
    [ "tesseract::UnicharIdArrayUtils", "a02930.html", null ],
    [ "UNICHARMAP", "a03102.html", null ],
    [ "tesseract::UnicharRating", "a03342.html", null ],
    [ "UNICHARSET", "a03118.html", null ],
    [ "UnicityTable< T >", "a02734.html", [
      [ "UnicityTableEqEq< T >", "a03130.html", null ]
    ] ],
    [ "UnicityTable< int >", "a02734.html", [
      [ "UnicityTableEqEq< int >", "a03130.html", null ]
    ] ],
    [ "UnicityTable< tesseract::FontInfo >", "a02734.html", null ],
    [ "UnicityTable< tesseract::FontSet >", "a02734.html", null ],
    [ "tesseract::UnicodeSpanSkipper", "a02590.html", null ],
    [ "UnicodeText", "a04346.html", null ],
    [ "tesseract::UnityFunc", "a03490.html", null ],
    [ "tesseract::Validator", "a03962.html", [
      [ "tesseract::ValidateGrapheme", "a03942.html", null ],
      [ "tesseract::ValidateIndic", "a03946.html", null ],
      [ "tesseract::ValidateJavanese", "a03950.html", null ],
      [ "tesseract::ValidateKhmer", "a03954.html", null ],
      [ "tesseract::ValidateMyanmar", "a03958.html", null ]
    ] ],
    [ "tesseract::WeightMatrix", "a03610.html", null ],
    [ "tesseract::WordData", "a02654.html", null ],
    [ "tesseract::WordFeature", "a02758.html", null ],
    [ "WordOutputter", "a03838.html", null ],
    [ "tesseract::WordWithBox", "a03802.html", null ]
];